# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => :static if linkage != nil

target 'FocusHaven' do
  config = use_native_modules!

  use_react_native!(
    :hermes_enabled => true,
    :new_arch_enabled => true,   # <-- match the ENV above
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Your extra pods
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNReanimated',  :path => '../node_modules/react-native-reanimated'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
